import time
import json
import os
import streamlit as st
import pandas as pd
import plotly.express as px
import umap.umap_ as umap
import numpy as np
from sklearn.manifold import trustworthiness
from utils.sphere_projection import project_embeddings_to_sphere


# CFG class: allows for reproducibility with the same results
class CFG:
    # Path files
    EMB_PATH = "embeddings/veltri/veltri_embeddings.npy"
    META_PATH = "embeddings/veltri/veltri_metadata.csv"
    VELTRI_PATH = "data/veltri/all_veltri.csv"
    # Default parameters (used as fallback if no Optuna JSON exists)
    n_neighbors = 5
    n_components = 3  # default to 3D so both plots show on load
    min_dist = 0.005527128631029834
    metric = "cosine"
    seed = 42


# --- Load best params from JSON files ---
OPTUNA_PARAMS = {}

# optuna_results/{dim}d_params.json (generated by optimize_umap.py)
for dim in [2, 3, 4, 5, 6, 7, 8]:
    path = f"optuna_results/{dim}d_params.json"
    if os.path.exists(path):
        with open(path) as f:
            data = json.load(f)
            OPTUNA_PARAMS[dim] = data["best_params"]


# --- Cached functions ---
@st.cache_data
def load_embeddings(file):
    return np.load(file).astype("float32")


@st.cache_data
def load_metadata(file):
    return pd.read_csv(file)


@st.cache_data
def run_umap(
    X,
    n_neighbors,
    min_dist,
    n_components,
    metric,
    seed,
    method,
    dens_lambda=None,
    dens_frac=None,
    dens_var_shift=None,
):
    reducer_kwargs = dict(
        n_neighbors=n_neighbors,
        min_dist=min_dist,
        n_components=n_components,
        metric=metric,
        random_state=seed,
    )

    if method == "densMAP":
        reducer_kwargs.update(
            densmap=True,
            dens_lambda=dens_lambda,
            dens_frac=dens_frac,
            dens_var_shift=dens_var_shift,
        )

    reducer = umap.UMAP(**reducer_kwargs)
    return reducer.fit_transform(X)


# --- Page setup ---
st.set_page_config(page_title="UMAP Peptide Embeddings", layout="wide")
st.title("UMAP/DensMAP — ProteoGPT - Veltri Embeddings")


# --- File uploaders ---
st.sidebar.header("Upload Local Files")
uploaded_embeddings = st.sidebar.file_uploader("Upload embeddings (.npy)", type=["npy"])
uploaded_metadata   = st.sidebar.file_uploader("Upload metadata (.csv)", type=["csv"])


# --- Data source selection ---
st.sidebar.header("Data Source")
meta_choice = st.sidebar.radio(
    "Metadata to use for labels/hover",
    ["Veltri metadata (recommended)", "Raw Veltri CSV (all_veltri.csv)"],
    index=0,
)
selected_meta_path = (
    CFG.META_PATH
    if meta_choice == "Veltri metadata (recommended)"
    else CFG.VELTRI_PATH
)


# --- Load embeddings ---
try:
    if uploaded_embeddings is not None:
        st.sidebar.success("Using uploaded embeddings")
        X = np.load(uploaded_embeddings).astype("float32")
        emb_source = "Uploaded .npy"
    else:
        X = np.load(CFG.EMB_PATH).astype("float32")
        emb_source = CFG.EMB_PATH
except Exception as e:
    st.error(f"Could not read embeddings: {e}")
    st.info(f"Default expected at: {CFG.EMB_PATH}")
    st.stop()

st.caption(f"Embeddings source: {emb_source}")


# --- Load metadata ---
try:
    if uploaded_metadata is not None:
        st.sidebar.success("Using uploaded metadata")
        meta = load_metadata(uploaded_metadata)
        meta_source = "Uploaded .csv"
    else:
        meta = load_metadata(selected_meta_path)
        meta_source = selected_meta_path
except Exception as e:
    st.error(f"Could not read metadata: {e}")
    st.stop()

st.caption(f"Metadata source: {meta_source}")


# --- Column detection helper ---
def pick_col(df: pd.DataFrame, candidates: list[str]) -> str | None:
    cols_lower = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in cols_lower:
            return cols_lower[cand.lower()]
    return None


seq_col   = pick_col(meta, ["sequence", "aa_seq", "seq", "peptide", "peptide_sequence", "amp_sequence"])
id_col    = pick_col(meta, ["peptide_id", "id", "identifier", "name", "entry", "accession"])
label_col = pick_col(meta, ["source", "label", "class", "family", "dataset", "type"])

st.sidebar.header("Column Override (if auto detection fails)")
cols = list(meta.columns)

if seq_col is None:
    st.sidebar.warning("Sequence column not detected automatically.")
    seq_col = st.sidebar.selectbox("Select sequence column", cols)

if id_col is None:
    id_choice = st.sidebar.selectbox("Select ID column (optional)", ["None"] + cols)
    if id_choice != "None":
        id_col = id_choice

if label_col is None:
    label_choice = st.sidebar.selectbox("Select label column (optional)", ["None"] + cols)
    if label_choice != "None":
        label_col = label_choice


# --- Build plotting dataframe ---
df = pd.DataFrame({
    "id":       meta[id_col].astype(str)    if id_col    else meta.index.astype(str),
    "label":    meta[label_col].astype(str) if label_col else "unknown",
    "sequence": meta[seq_col].astype(str)   if seq_col   else "",
})

if "is_amp" in meta.columns:
    df["is_amp"] = meta["is_amp"].astype(bool)
elif "AMP" in meta.columns:
    df["is_amp"] = meta["AMP"].astype(int).eq(1)
else:
    df["is_amp"] = False


# --- Row safety check ---
nX, nM = X.shape[0], df.shape[0]
if nX != nM:
    st.warning(f"Row mismatch: embeddings {nX} vs metadata {nM}")
    n  = min(nX, nM)
    X  = X[:n]
    df = df.iloc[:n]


# --- UMAP Settings ---
st.sidebar.header("UMAP Settings")

# Sphere dimension: controls the 3D sphere projection only.
# The 2D plot always uses a separate 2D UMAP run.
sphere_dims = st.sidebar.selectbox(
    "Sphere Dimensions (3D plot)",
    options=[3, 4, 5, 6, 7, 8],
    index=0,
    help="Controls how many dimensions UMAP reduces to before projecting onto the sphere. The 2D plot always uses 2D UMAP independently."
)

if sphere_dims not in OPTUNA_PARAMS:
    st.sidebar.warning(
        f"No Optuna results found for {sphere_dims}D — parameters not validated."
    )

# --- Auto-apply best params when sphere dimension changes ---
if st.session_state.get("_last_sphere_dims") != sphere_dims:
    st.session_state["_last_sphere_dims"] = sphere_dims
    if sphere_dims in OPTUNA_PARAMS:
        best = OPTUNA_PARAMS[sphere_dims]
        st.session_state["nn_slider"] = best["n_neighbors"]
        st.session_state["md_slider"] = float(best["min_dist"])
        st.session_state["method_radio"] = best["method"].split()[0]
        st.session_state["dl_slider"] = float(best.get("dens_lambda", 2.0))
    else:
        st.session_state.setdefault("nn_slider", CFG.n_neighbors)
        st.session_state.setdefault("md_slider", float(CFG.min_dist))
        st.session_state.setdefault("method_radio", "UMAP")
        st.session_state.setdefault("dl_slider", 2.0)

# --- Parameter inputs: synced slider + number input ---
st.sidebar.markdown("**n_neighbors**")
col1, col2 = st.sidebar.columns([3, 1])
nn = col1.slider("##nn_slider", 2, 200, key="nn_slider", label_visibility="collapsed")
CFG.n_neighbors = col2.number_input(
    "##nn_input", value=nn, min_value=2, step=1, label_visibility="collapsed"
)

st.sidebar.markdown("**min_dist**")
col1, col2 = st.sidebar.columns([3, 1])
md = col1.slider("##md_slider", 0.0, 1.0, step=0.001, key="md_slider", label_visibility="collapsed")
CFG.min_dist = col2.number_input(
    "##md_input", value=md, min_value=0.0, max_value=1.0, step=0.001,
    format="%.4f", label_visibility="collapsed"
)


# --- Embedding method ---
st.sidebar.header("Embedding Method")
method = st.sidebar.radio("Projection Type", ["UMAP", "densMAP"], key="method_radio")

dens_lambda = dens_frac = dens_var_shift = None

if method == "densMAP":
    st.sidebar.markdown("**dens_lambda**")
    col1, col2 = st.sidebar.columns([3, 1])
    dl = col1.slider("##dl_slider", 0.0, 10.0, key="dl_slider", label_visibility="collapsed")
    dens_lambda = col2.number_input(
        "##dl_input", value=dl, min_value=0.0, step=0.1, label_visibility="collapsed"
    )

    st.sidebar.markdown("**dens_frac**")
    col1, col2 = st.sidebar.columns([3, 1])
    df_ = col1.slider("##df_slider", 0.0, 1.0, 0.3, label_visibility="collapsed")
    dens_frac = col2.number_input(
        "##df_input", value=df_, min_value=0.0, max_value=1.0,
        step=0.01, label_visibility="collapsed"
    )

    st.sidebar.markdown("**dens_var_shift**")
    col1, col2 = st.sidebar.columns([3, 1])
    dvs = col1.slider("##dvs_slider", 0.0, 1.0, 0.1, label_visibility="collapsed")
    dens_var_shift = col2.number_input(
        "##dvs_input", value=dvs, min_value=0.0, max_value=1.0,
        step=0.01, label_visibility="collapsed"
    )


# --- 3D visualization controls ---
st.sidebar.header("3D Visualization")
point_size = st.sidebar.slider("Point size", 1, 10, 3)
opacity    = st.sidebar.slider("Opacity", 0.1, 1.0, 0.7, 0.05)
zoom       = st.sidebar.slider("Zoom", 0.5, 3.0, 1.5, 0.1)


# --- 2D selection mode ---
st.sidebar.header("Region Selection (2D)")
select_mode = st.sidebar.radio(
    "Selection Mode",
    ["pan", "box", "lasso"],
    index=0,
    help="Box/lasso: draw on the 2D plot — selected peptides are highlighted on the 3D sphere"
)



# RUN UMAP — two separate runs: one 2D (for the flat scatter), one nD (for sphere)
# Both share the same n_neighbors, min_dist, metric, seed, and method.

st.sidebar.info("Two UMAP runs execute per update: one 2D and one for the sphere dimension selected.")

start_2d = time.time()
X_umap_2d = run_umap(
    X, CFG.n_neighbors, CFG.min_dist, 2,
    CFG.metric, CFG.seed, method,
    dens_lambda, dens_frac, dens_var_shift,
)
runtime_2d = time.time() - start_2d

start_nd = time.time()
X_umap_nd = run_umap(
    X, CFG.n_neighbors, CFG.min_dist, sphere_dims,
    CFG.metric, CFG.seed, method,
    dens_lambda, dens_frac, dens_var_shift,
)
runtime_nd = time.time() - start_nd


# --- Baseline metrics ---
st.subheader("Baseline metrics")
st.write("Rows:", X.shape[0])
st.write("Embedding dim:", X.shape[1])
mc1, mc2 = st.columns(2)
mc1.write(f"2D {method} runtime: {runtime_2d:.3f}s")
mc2.write(f"{sphere_dims}D {method} runtime: {runtime_nd:.3f}s")


# --- Trustworthiness ---
st.subheader("Embedding Quality")
trust_2d = trustworthiness(X, X_umap_2d, n_neighbors=CFG.n_neighbors)
trust_nd = trustworthiness(X, X_umap_nd, n_neighbors=CFG.n_neighbors)

tc1, tc2 = st.columns(2)
tc1.metric("Trustworthiness 2D", f"{trust_2d:.4f}")
tc2.metric(f"Trustworthiness {sphere_dims}D", f"{trust_nd:.4f}")

# Show warning/success based on the lower of the two scores
min_trust = min(trust_2d, trust_nd)
if min_trust >= 0.90:
    st.success(f"Both embeddings good — local structure well preserved")
elif min_trust >= 0.75:
    st.warning(f"Moderate embedding quality — some structure lost")
else:
    st.error(f"Poor embedding quality — significant structure lost")



# 2D PLOT — always rendered, acts as the selection tool
st.subheader("2D Projection — Selection Tool")
st.caption("Use box or lasso mode to select peptides. Your selection is highlighted on the 3D sphere below.")

plot_df = pd.DataFrame({
    "UMAP1":      X_umap_2d[:, 0],
    "UMAP2":      X_umap_2d[:, 1],
    "peptide_id": df["id"],
    "sequence":   df["sequence"],
    "is_amp":     df["is_amp"],
})

fig_2d = px.scatter(
    plot_df,
    x="UMAP1", y="UMAP2",
    color="is_amp",
    color_discrete_map={False: "blue", True: "red"},
    hover_data=["peptide_id", "sequence", "is_amp"],
    title=f"{method} 2D projection",
)
fig_2d.update_traces(marker=dict(size=4, opacity=0.6))

drag_map = {"pan": "pan", "box": "select", "lasso": "lasso"}
fig_2d.update_layout(
    dragmode=drag_map.get(select_mode, "select"),
    xaxis=dict(range=[float(X_umap_2d[:, 0].min()) - 1, float(X_umap_2d[:, 0].max()) + 1]),
    yaxis=dict(range=[float(X_umap_2d[:, 1].min()) - 1, float(X_umap_2d[:, 1].max()) + 1]),
    height=550,
)

event_2d = st.plotly_chart(
    fig_2d,
    use_container_width=True,
    on_select="rerun",
    key="umap_2d_plot",
)

# Extract selected indices and persist in session_state so the 3D plot
# can read them even after Streamlit reruns triggered by other widgets
selected_points_2d = []
if event_2d and hasattr(event_2d, "selection") and event_2d.selection:
    selected_points_2d = event_2d.selection.get("points", [])

if selected_points_2d:
    st.session_state["selected_indices"] = [p["point_index"] for p in selected_points_2d]
    st.session_state["selected_bbox"] = {
        "x_min": round(min(p["x"] for p in selected_points_2d), 4),
        "x_max": round(max(p["x"] for p in selected_points_2d), 4),
        "y_min": round(min(p["y"] for p in selected_points_2d), 4),
        "y_max": round(max(p["y"] for p in selected_points_2d), 4),
    }

# Read persisted selection (survives reruns from dimension switcher etc.)
selected_indices = st.session_state.get("selected_indices", [])
selected_bbox    = st.session_state.get("selected_bbox", None)

# Show 2D selection summary
if selected_indices:
    selected_df = df.iloc[selected_indices].copy()
    amp_count     = int(selected_df["is_amp"].sum())
    non_amp_count = len(selected_df) - amp_count

    st.subheader(f"Selected — {len(selected_indices)} peptides")
    st.caption(f"AMPs: {amp_count} | Non-AMPs: {non_amp_count}")

    if selected_bbox:
        st.json(selected_bbox)

    col_save, col_clear = st.columns([1, 1])
    with col_save:
        if st.button("Save 2D Selection"):
            save_path = f"selections/2d_selection_{int(time.time())}.json"
            os.makedirs("selections", exist_ok=True)
            with open(save_path, "w") as f_out:
                json.dump({
                    "bbox": selected_bbox,
                    "params": {
                        "n_neighbors": CFG.n_neighbors,
                        "min_dist":    CFG.min_dist,
                        "method":      method,
                    },
                    "selected_ids": selected_df["id"].tolist(),
                }, f_out, indent=2)
            st.success(f"Saved to {save_path}")
    with col_clear:
        if st.button("Clear Selection"):
            st.session_state.pop("selected_indices", None)
            st.session_state.pop("selected_bbox", None)
            st.rerun()

else:
    if select_mode in ["box", "lasso"]:
        st.info("Draw a region on the 2D plot above to highlight peptides on the sphere below.")



# 3D SPHERE PLOT — always rendered, highlights whatever is selected in 2D
st.divider()
st.subheader(f"3D Sphere — {sphere_dims}D Projection")
st.caption(
    f"Showing the {sphere_dims}D UMAP output projected onto a unit sphere. "
    "Red = selected in 2D plot. Grey = not selected. Blue/Red = AMP coloring when no selection active."
)

X_sphere = project_embeddings_to_sphere(X_umap_nd)

sphere_df = pd.DataFrame({
    "x":        X_sphere[:, 0],
    "y":        X_sphere[:, 1],
    "z":        X_sphere[:, 2],
    "id":       df["id"],
    "sequence": df["sequence"],
    "is_amp":   df["is_amp"],
})

if selected_indices:
    # Mark which points were selected in the 2D plot
    sphere_df["selected"] = False
    sphere_df.loc[selected_indices, "selected"] = True

    fig_3d = px.scatter_3d(
        sphere_df,
        x="x", y="y", z="z",
        color="selected",
        color_discrete_map={
            True:  "red",
            False: "rgba(120,120,120,0.15)",
        },
        hover_data=["id", "sequence", "is_amp"],
        title=f"{method} {sphere_dims}D sphere | {len(selected_indices)} peptides selected from 2D",
    )
else:
    # No selection — render with normal AMP/non-AMP coloring
    fig_3d = px.scatter_3d(
        sphere_df,
        x="x", y="y", z="z",
        color="is_amp",
        color_discrete_map={False: "blue", True: "red"},
        hover_data=["id", "sequence", "is_amp"],
        title=f"{method} {sphere_dims}D sphere",
    )

fig_3d.update_traces(marker=dict(size=point_size, opacity=opacity))
fig_3d.update_layout(
    height=700,
    scene=dict(
        aspectmode="cube",
        xaxis=dict(showgrid=False, zeroline=False),
        yaxis=dict(showgrid=False, zeroline=False),
        zaxis=dict(showgrid=False, zeroline=False),
    ),
    scene_camera=dict(eye=dict(x=zoom, y=zoom, z=zoom)),
)

st.caption("💡 Tip: Two-finger scroll to zoom, drag to rotate, right-click drag to pan. Use ⛶ in the toolbar to fullscreen.")
st.plotly_chart(fig_3d, use_container_width=True)

# Show selected peptides table below the 3D plot if a selection is active
if selected_indices:
    st.subheader(f"Selected Peptides on Sphere ({sphere_dims}D)")
    selected_sphere = sphere_df[sphere_df["selected"] == True][["id", "sequence", "is_amp", "x", "y", "z"]]
    selected_sphere[["x", "y", "z"]] = selected_sphere[["x", "y", "z"]].round(4)
    st.dataframe(selected_sphere, use_container_width=True)

    if st.button("Save 3D Sphere Coordinates"):
        save_path = f"selections/3d_sphere_{sphere_dims}d_{int(time.time())}.json"
        os.makedirs("selections", exist_ok=True)
        with open(save_path, "w") as f_out:
            json.dump({
                "sphere_dims": sphere_dims,
                "n_selected":  len(selected_indices),
                "params": {
                    "n_neighbors": CFG.n_neighbors,
                    "min_dist":    CFG.min_dist,
                    "method":      method,
                },
                "selected_ids": df.iloc[selected_indices]["id"].tolist(),
                "sphere_coords": selected_sphere[["id", "x", "y", "z"]].to_dict(orient="records"),
            }, f_out, indent=2)
        st.success(f"Saved to {save_path}")


# --- Clear cache ---
if st.sidebar.button("Clear Cache"):
    st.cache_data.clear()
    st.success("Cache cleared!")